Задача "Вычислить факториал"
js-tasks-ru/jsbasic-20220310_valera-mashenets pull request #2
Opened 2022-03-15 12:43 UTC by webvalery

2022-03-15 12:44 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-03-15 15:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-15 16:05 UTC, koalex requested changes
Я не смогу принять PR пока не будет решена **1-module-3-task**

2022-03-16 06:20 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-03-16 08:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-03-17 03:19 UTC, koalex approved these changes

2022-03-17 03:20 UTC, merged